# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
    ansible.galaxy_role_file = "roles.yml"
  end

  config.vm.define "test01" do |node|
    node.vm.network "private_network", ip: "10.0.0.2"

    node.vm.box = "jeqo/ansible-centos7"
  end

  config.vm.define "test02" do |node|
    node.vm.network "private_network", ip: "10.0.0.3"

    node.vm.box = "jeqo/ansible-centos7"
  end

  config.vm.define "test03" do |node|
    node.vm.network "private_network", ip: "10.0.0.2"

    node.vm.box = "jeqo/ansible-ubuntu14"
  end

  config.vm.define "test04" do |node|
    node.vm.network "private_network", ip: "10.0.0.3"

    node.vm.box = "jeqo/ansible-ubuntu14"
  end
end
